### ISSUE TITLE
Error Title: NullPointerException in InventoryTransactionPacket Handling

### ISSUE THREAD

**Issue by m3fri** [MemoriesOfTime/Nukkit-MOT#121] opened 2023-12-02 09:24 UTC
# 🐞 Bug Feedback | BUG反馈

📝 Bug Description | BUG描述
An error occurred while handling the InventoryTransactionPacket for a player named "Steve4fr." The stack trace points to a NullPointerException in the ItemCrossbow class at lines 103 and 77, as well as in the Player class at line 4530. This error occurs during the execution of the serverTick method in the RakNetPlayerSession class.

🔍 Possible Cause | 可能的原因
The NullPointerException is thrown when attempting to invoke the setName method on a CompoundTag object, but the object itself is null. This issue is occurring in the context of the ItemCrossbow class during the loading of an arrow and its usage.

💻 OS and versions | 操作系统和核心版本
Nukkit-MOT master/8cac79a
Version: 1.20.40 (protocol 622)
Java: OracleJDK
Java version: 17
Platform: win10

```error
12:03:51 [ERROR] An error occurred whilst handling InventoryTransactionPacket for Steve4fr
java.lang.NullPointerException: Cannot invoke "cn.nukkit.nbt.tag.CompoundTag.setName(String)" because "value" is null
        at cn.nukkit.nbt.tag.CompoundTag.putCompound(CompoundTag.java:168) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.item.ItemCrossbow.loadArrow(ItemCrossbow.java:103) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.item.ItemCrossbow.onUse(ItemCrossbow.java:77) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:4530) ~[Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:199) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:95) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:119) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1402) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1136) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:1104) [Nukkit-MOT-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:818) [Nukkit-MOT-SNAPSHOT.jar:?]
```

**Comment by lt-name** [comment] 2023-12-02 10:40
Duplicate of https://github.com/MemoriesOfTime/Nukkit-MOT/issues/112

**Closed by lt-name** 2023-12-02 10:40 UTC
